apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: reverse-words
  namespace: reverse-words
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: reverse-words
    weight: 100
