apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    type: elasticsearch
    retentionPolicy:
      application:
        maxAge: 2d
      infra:
        maxAge: 3d
      audit:
        maxAge: 5d
    elasticsearch:
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 4Gi
      nodeCount: 1
      nodeSelector:
        node-role.kubernetes.io/logging: ""
      redundancyPolicy: ZeroRedundancy
      storage:
        storageClassName: gp2
        size: 30Gi
      tolerations:
      - key: logging
        value: reserved
        effect: NoSchedule
      - key: logging
        value: reserved
        effect: NoExecute
  visualization:
    type: kibana
    kibana:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io/logging: ""
      tolerations:
      - key: logging
        value: reserved
        effect: NoSchedule
      - key: logging
        value: reserved
        effect: NoExecute
  curation:
    type: curator
    curator:
      schedule: 30 3 * * *
      nodeSelector:
        node-role.kubernetes.io/logging: ""
      tolerations:
      - key: logging
        value: reserved
        effect: NoSchedule
      - key: logging
        value: reserved
        effect: NoExecute
  collection:
    logs:
      type: fluentd
      fluentd:
        tolerations:
        - operator: Exists
