apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    openshift.io/node-selector: ""
    argocd.argoproj.io/hook: PreSync
  labels:
    openshift.io/cluster-monitoring: "true"
