apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    openshift.io/node-selector: ""
    argocd.argoproj.io/hook: PreSync
  labels:
    openshift.io/cluster-monitoring: "true"
