apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    release.openshift.io/create-only: "true"
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster
spec:
  projectRequestTemplate:
    name: project-request
