apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JFUvbkpaWXl5YndIQkIwbHU0aVlta09FaUdieEhTTk1landQZVM1aHZ6d2NXbmIzSDlSNTg2Cg==
kind: Secret
metadata:
  name: htpasswd
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
